name: <your project name>
services:
    asterisk:
        container_name: c_asterisk
        ports:
            - 5060:5060/udp
        volumes:
            - asterisk_conf:/etc/asterisk
        image: asterisk
    dnsmasq:
        container_name: c_dns
        ports:
            - 53:53/udp
            - 53:53
        volumes:
            - ./dnsmasq.conf:/etc/dnsmasq.conf
        cap_add:
            - NET_ADMIN
        image: andyshinn/dnsmasq
volumes:
    asterisk_conf:
        external: true
        name: asterisk_conf