name: Projet_TRI
services:
    asterisk:
        container_name: c_asterisk
        ports:
            - 5060:5060/udp
        volumes:
            - asterisk_conf:/etc/asterisk
        image: quebotek/monasterisk
    dns:
        build: .
        restart: 'unless-stopped'
        volumes:
        - '/etc/localtime:/etc/localtime:ro'
        - './dnsmasq.conf:/etc/dnsmasq.conf:ro'
        ports:
        - '53:53/tcp'
        - '53:53/udp'
volumes:
    asterisk_conf:
        external: true
        name: asterisk_conf
