name: <your project name>
services:
    monasterisk:
        container_name: c_asterisk
        ports:
            - 5060:5060/udp
            - 10000-20000:10000-20000
        volumes:
            - asterisk_conf:/etc/asterisk
        image: quebotek/monasterisk
volumes:
    asterisk_conf:
        external: true
        name: asterisk_conf