name: <your project name>
services:
    monasterisk:
        container_name: c_asterisk
        ports:
            - 5060:5060/udp
        volumes:
            - asterisk_conf:/etc/asterisk
        image: quebotek/monasterisk
    dns:
        container_name: c_dns
        environment:
            - DNS_DOMAIN=.projet
            - DNS_IP=10.1.1.2
        image: docksal/dns
volumes:
    asterisk_conf:
        external: true
        name: asterisk_conf