name: asterisk
services:
    monasterisk:
        container_name: c_monasterisk
        ports:
            - 5060:5060/udp
        volumes:
            - asterisk_conf:/etc/asterisk
        image: monasterisk
volumes:
    asterisk_conf:
        external: true
        name: asterisk_conf