name: <your project name>
services:
    monasterisk:
        container_name: c_asterisk
        ports:
            - 5060:5060/udp
        volumes:
            - asterisk_conf:/etc/asterisk
        image: quebotek/monasterisk
    docker-merlin-dns:
        container_name: c_dns
        cap_add:
            - NET_ADMIN
        ports:
            - 53:53
            - 53:53/udp
            - 67:67/udp
        image: sitipati/docker-merlin-dns
volumes:
    asterisk_conf:
        external: true
        name: asterisk_conf