name: Projet_TRI
services:
    monasterisk:
        container_name: c_asterisk
        ports:
            - 5060:5060/udp
        volumes:
            - asterisk_conf:/etc/asterisk
        image: quebotek/monasterisk
volumes:
    asterisk_conf:
        external: true
        name: asterisk_conf